analyzer:
  plugins:
    - custom_lint

custom_lint:
  rules:
    - prefer_named_parameters:
      threshold: 2
      severity: warning
    - incorrect_todo_comment:
      excludes:
      - "lib/excluded_test/incorrect_todo_comment_excluded_test.dart"
      severity: error
    - prefer_is_empty_string:
      severity: warning
    - prefer_is_not_empty_string:
      severity: warning
    - avoid_unnecessary_async_function:
      severity: warning
    - prefer_async_await:
      excludes:
      - "**excluded_test.dart"
      severity: warning
    - prefer_lower_case_test_description:
      severity: warning
      test_methods:
        - method_name: 'test'
          param_name: 'description'
        - method_name: 'blocTest'
          param_name: 'desc'
    - test_folder_must_mirror_lib_folder:
      severity: warning
      lib_folder_path: "lib/test_folder_must_mirror_lib_folder_test/lib"
      test_folder_paths:
        - "lib/test_folder_must_mirror_lib_folder_test/test/ut"
        - "lib/test_folder_must_mirror_lib_folder_test/it"
    - incorrect_parent_class:
      severity: warning
      class_post_fixes:
        - 'Page'
        - 'Screen'
      parent_class_pre_fixes:
        - 'Base'
        - 'Abstract'
    - prefer_importing_index_file:
      severity: warning
    - missing_expanded_or_flexible:
      severity: warning
    - avoid_using_text_style_constructor_directly:
    - util_functions_must_be_static:
      severity: warning
      utils_folder_path: "lib/util_functions_must_be_static_test/utils"
    - missing_run_catching:
      severity: warning
    - avoid_using_if_else_with_enums:
      severity: warning
    - avoid_nested_conditions:
      severity: warning
      acceptable_level: 3
    - missing_log_in_catch_block:
      severity: warning
      class_name: "Log"
      methods:
        - "severe"
        - "warning"
        - "info"
        - "debug"
        - "error"
    - missing_extension_method_for_events:
    - missing_common_scrollbar:
      excludes:
        - "test/*.dart"
        - "test/**/*.dart"
        - "integration_test/*.dart"
        - "integration_test/**/*.dart"
      common_scrollbar_widget_name: "CommonScrollbar"
    - avoid_dynamic:
      severity: warning
    - avoid_hard_coded_colors:
    - prefer_common_widgets:
    - avoid_hard_coded_strings:
    - incorrect_screen_name_parameter_value:
    - incorrect_screen_name_enum_value:
    - incorrect_event_parameter_name:
    - incorrect_event_parameter_type:
    - incorrect_event_name:
    - avoid_using_unsafe_cast:
    - prefer_single_widget_per_file:
