name: Check Review Comments and Mentions

on:
  pull_request:
    types: [opened, edited, synchronize]

env:
  EXCLUDED_USERS: '["Copilot", "coderabbitai[bot]", "cursor[bot]"]'

jobs:
  check-review-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and check review comments
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔍 Getting PR info..."
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}

          echo "📥 Fetching all review comments..."
          gh api repos/$REPO/pulls/$PR_NUMBER/comments --paginate > all_comments.json

          PR_AUTHOR=$(gh api repos/$REPO/pulls/$PR_NUMBER --jq '.user.login')
          echo "👤 PR Author: $PR_AUTHOR"

          echo "🧾 Filtering root comments (excluding PR author & excluded users)..."
          echo "$EXCLUDED_USERS" > excluded_users.json
          jq --arg author "$PR_AUTHOR" --argjson excluded "$(cat excluded_users.json)" '
            [.[] 
              | select(
                  .in_reply_to_id == null
                  and .user.login != $author
                  and (.user.login as $u | $excluded | index($u) | not)
              )
            ]' all_comments.json > root_comments.json
          ROOT_COUNT=$(jq length root_comments.json)
          echo "🔢 Total Root Review Comments: $ROOT_COUNT"

          echo "🔁 Filtering replies with @mention from non-excluded users..."
          jq --argjson excluded "$(cat excluded_users.json)" '
            [.[] 
              | select(
                  .in_reply_to_id != null
                  and (.user.login as $u | $excluded | index($u) | not)
                  and (.body | test("@"; "i"))
              )
            ]' all_comments.json > replies_with_mentions.json
          MENTION_COUNT=$(jq length replies_with_mentions.json)
          echo "💬 Reply mentions count: $MENTION_COUNT"

          echo "📊 Summary:"
          echo "🧮 Root Comments (need reply): $ROOT_COUNT"
          echo "💬 Mentions: $MENTION_COUNT"

          if [ "$MENTION_COUNT" -lt "$ROOT_COUNT" ]; then
            echo "❌ Not enough replies for the root comments."
            exit 1
          else
            echo "✅ All root comments are properly replied with @mention."
          fi
