name: Check Review Comments and Mentions

on:
  pull_request:
    types: [opened, edited, synchronize]

env:
  EXCLUDED_USERNAMES: '["Copilot", "coderabbitai[bot]"]'

jobs:
  check-review-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch and check review comments
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          EXCLUDED_USERS='${{ env.EXCLUDED_USERNAMES }}'

          echo "🔍 Getting PR info..."
          PR_AUTHOR=$(gh api repos/$REPO/pulls/$PR_NUMBER --jq '.user.login')
          echo "👤 PR Author: $PR_AUTHOR"

          echo "📥 Fetching all review comments..."
          gh api repos/$REPO/pulls/$PR_NUMBER/comments --paginate > all_comments.json

          echo "🧾 Filtering root comments (excluding PR author & excluded users)..."
          jq --argjson excluded "$EXCLUDED_USERS" --arg author "$PR_AUTHOR" '
            [.[] | select(.in_reply_to_id == null and .user.login != $author and (.user.login | IN(excluded[]) | not))]
          ' all_comments.json > root_comments.json
          ROOT_COUNT=$(jq length root_comments.json)
          echo "🔢 Total Root Review Comments (valid authors): $ROOT_COUNT"

          echo "🔁 Counting valid mentions in replies..."
          jq --argjson excluded "$EXCLUDED_USERS" '
            [.[] | select(.in_reply_to_id != null and (.user.login | IN(excluded[]) | not) and (.body | test("@"; "i")))]
          ' all_comments.json > replies_with_mentions.json

          # Extract all @mentions
          jq -r '.[] | .body' replies_with_mentions.json | grep -o "@[a-zA-Z0-9_\[\]\-]\+" | sort | uniq -c > mention_stats.txt
          echo "📄 Mention Stats:"
          cat mention_stats.txt

          # Count total @mentions (excluding bots)
          MENTION_COUNT=$(cat mention_stats.txt | wc -l | xargs)
          echo "🔁 Total distinct valid mentions: $MENTION_COUNT"

          echo "📊 Summary:"
          echo "🧮 Root Comments (from valid authors): $ROOT_COUNT"
          echo "💬 Mentions in replies: $MENTION_COUNT"

          if [ "$MENTION_COUNT" -lt "$ROOT_COUNT" ]; then
            echo "❌ Not enough mentions for the number of root comments."
            exit 1
          else
            echo "✅ All checks passed."
          fi
